structurizr:
  workspace:
    id: 11111
    name: DRestaurnat - Monolith
    description: This is a sample workspace of digital restaurant - monolith
    key: YOUR_KEY
    secret: YOUR_SECRET
  #   Whether to put the workspace to the structurizr server after the model has been fully initialized.
  performMerge: false
spring:
  data:
    rest:
      base-path: /api/query
  datasource:
    url: jdbc:h2:mem:restaurant
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  eventhandling:
    processors:
      customer:
        mode: tracking
      restaurant:
        mode: tracking
      order:
        mode: tracking
      courier:
        mode: tracking
  snapshot:
    trigger:
      treshold:
        order: 100
        restaurant: 100
        customer: 100
        courier: 100
        customerorder: 100
        courierorder: 100
        restaurantorder: 100
