server:
  port: 8081
spring:
  application:
    name: command-courier
  datasource:
    url: jdbc:h2:mem:restaurant-courier
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  snapshot:
    trigger:
      treshold:
        courier: 100
        courierorder: 100
  kafka:
    #    client-id: courier-command
    default-topic: axon-events
    producer:
      retries: 5
      bootstrap-servers: localhost:9092
      transaction-id-prefix: couriertx
    consumer:
      group-id: courier-command-group
      bootstrap-servers: localhost:9092
  distributed:
    enabled: true
  serializer:
    messages: xstream



