server:
  port: 8082
spring:
  application:
    name: command-customer
  datasource:
    url: jdbc:h2:mem:restaurant-customer
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  snapshot:
    trigger:
      treshold:
        customer: 100
        customerorder: 100
  kafka:
    #    client-id: customer-command
    default-topic: axon-events
    producer:
      retries: 5
      bootstrap-servers: localhost:9092
      transaction-id-prefix: customertx
    consumer:
      group-id: customer-command-group
      bootstrap-servers: localhost:9092
  distributed:
    enabled: true
  serializer:
    messages: xstream

