server:
  port: 8085
spring:
  application:
    name: query
  datasource:
    url: jdbc:h2:mem:restaurant-query
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
#All processors are 'tracking' by default, you can remove this!
axon:
  eventhandling:
    processors:
      customer:
        mode: tracking
      restaurant:
        mode: tracking
      order:
        mode: tracking
      courier:
        mode: tracking
      courierorder:
        mode: tracking
      restaurantorder:
        mode: tracking


