structurizr:
  workspace:
    id: 33333
    name: DRestaurnat - Monolith - Websockets
    description: This is a sample workspace of digital restaurant - monolith - websockets
    key: YOUR_KEY
    secret: YOUR_SECRET
  #  Whether to put the workspace to the structurizr server after the model has been fully initialized.
  performMerge: false
spring:
  datasource:
    url: jdbc:h2:mem:restaurant
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  eventhandling:
    processors:
      customer:
        mode: tracking
      restaurant:
        mode: tracking
      order:
        mode: tracking
      courier:
        mode: tracking
      courierorder:
        mode: tracking
      restaurantorder:
        mode: tracking
  snapshot:
    trigger:
      treshold:
        order: 100
        restaurant: 100
        customer: 100
        courier: 100
        customerorder: 100
        courierorder: 100
        restaurantorder: 100