server:
  port: 8084
spring:
  application:
    name: restaurant
    sagaqueue: restaurant.saga.event.stream
  rabbitmq:
    hostname: 127.0.0.1
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:restaurant-restaurant
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
axon:
  snapshot:
    trigger:
      treshold:
        restaurant: 100
        restaurantorder: 100
  amqp:
    exchange: events.fanout.exchange
  distributed:
    spring-cloud:
      fallback-to-http-get: false
    enabled: true





